@MovieAPI_HostAddress = https://localhost:7221

GET {{MovieAPI_HostAddress}}/api/v1/movies

### 

@id=2
GET {{MovieAPI_HostAddress}}/api/v1/movies/{{id}}

###

@id1=2
GET {{MovieAPI_HostAddress}}/api/v2/movies/{{id1}}/details

###

@id2=2
GET {{MovieAPI_HostAddress}}/api/v2/movies/{{id2}}/reviews

###

PUT {{MovieAPI_HostAddress}}/api/v1/movies/2
Content-Type: application/json

{
  "title": "Monty Python's Life of Brian",
  "year": "1979 ",
  "duration": "99 min",
  "details": {
    "synopsis": "The film's themes of religious satire were controversial at the time of its release, drawing accusations of blasphemy and protests from some religious groups..",
    "language": "Engelska",
    "budget": "$4 million"
  },
  "actors": [
    {
      "name": "Graham Chapman",
      "birthYear": "1941"
    },
    {
      "name": "John E Cleese",
      "birthYear": "1939"
    },
    {
      "name": "Eric Idle",
      "birthYear": "1943"
    }
  ],
  "genres": [
    {
      "genreName": "ComedyII"
    },
    {
      "genreName": "Satire"
    }
  ],
  "reviews": [
    {
      "reviewerName": "Adam T Brannon",
      "comment": "After last year’s bitterly disappointing Once Upon A Time in Hollywood bla bla.",
      "rating": 4
    }
  ]
}

###

POST {{MovieAPI_HostAddress}}/api/v1/movies
Content-Type: application/json

{
  "title": "Sällskapsresan II",
  "year": "1989",
  "duration": "107 min",
  "details": {
    "synopsis": "Stig-Helmer åker på charterresa till den fiktiva orten Nueva Estocolmo (’Nya Stockholm’) på Gran Canaria. Huvudberättelsen kretsar kring Stig-Helmer Olsson (Lasse Åberg) och norrmannen Ole Bramserud (Jon Skolmen), som av en slump hamnar bredvid varandra på flygplanet och sedan också tvingas dela hotellrum.",
    "language": "Svenska",
    "budget": "3 MSEK"
  },
  "actors": [
    {
      "name": "Lasse Åberg",
      "birthYear": "1940"
    },
    {
      "name": "Jon Skolmen",
      "birthYear": "1940"
    }
  ],
  "genres": [
    {
      "genreName": "Comedy"
    },
    {
      "genreName": "Satire"
    }
  ],
  "reviews": [
    {
      "reviewerName": "Martin Söderström - Aftonbladet",
      "comment": "Sällskapsresan – filmerna tillhör några av svensk films största framgångar någonsin. Bara den första filmen i serien sågs av 2,8 miljoner svenskar på bio – och hela serien har spelat in över 300 miljoner kronor.",
      "rating": 4
    }
  ]
}

###
@delid=9
DELETE {{MovieAPI_HostAddress}}/api/v1/movies/{{delid}}

