@MovieAPI_HostAddress = https://localhost:7221

GET {{MovieAPI_HostAddress}}/api/reviews

###
@getId=1

GET {{MovieAPI_HostAddress}}/api/reviews/{{getId}}

###
@postId=2

POST {{MovieAPI_HostAddress}}/api/reviews/{{postId}}
Content-Type: application/json

{
  "title": "Monty Python's Life of Brian",
  "reviewerName": "Lars Karlqvist",
  "comment": "Nästan rolig... hahaha.",
  "rating": 3
}

###
@putId=2

PUT {{MovieAPI_HostAddress}}/api/reviews/{{putId}}
Content-Type: application/json

  {
    "title": "Monty Python's Life of Brian",
    "reviewerName": "Adam Brannon",
    "comment": "After last year’s bitterly disappointing Once Upon A Time in Hollywood bla bla.",
    "rating": 4
  }

###
@delid=11

DELETE {{MovieAPI_HostAddress}}/api/reviews/{{delid}}

###
